-- DROP ALL OBJECTS; -- commande h2 pour réinitialiser la base

CREATE SEQUENCE vin_id_seq start with 1 increment 1;
CREATE TABLE vin (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chateau VARCHAR(50) NOT NULL,
    appellation VARCHAR(50),
    prix NUMERIC(10, 2)
);
ALTER SEQUENCE vin_id_seq increment by 100;

